---
subtitle: "Philip Morgan Consulting Client Briefing"
title: "Learning about book publishing"
author: "Philip Morgan"
date: TODO - v1.0
abstract: |
  I've been learning about professional self-publishing from someone who runs a boutique imprint. In this briefing I share what I've learned with you.
fontsize: 13pt
urlcolor: blue
output:
  tufte::tufte_handout:
    toc: true
    toc_depth: 3
  tufte::tufte_html:
    toc: true
    toc_depth: 3
---

# Introduction


# Raw Notes

# publishing

- cover design - faceout studiod
- front matter - mirror trad pub
- Quality of printing
- 28lb writing/text
- Page lifter helps
- Think about shipping cost
- Print on pre-drilled paper
- Need to shrink wrap them
- microsite just for book
- inbound
- Digital marketer in Austin
- Taan based out of Boston, Peter giertz
- Do play the blurb game
    - 2 or 3w deadline
    - Word count for blurb
  - create vanity publishing company name
  - Get pro author portrait
  - Sample chapter opt in is good
  - Include front and back matter in sample
  - Check out Marcus dePaula's wide: mixtus media
  - Ask ~20 people for blurbs
  - There is a paid book reviewing service, ask David for details
  - launch is important, esp if you offer a special price
  - Do cate about social media amplification
  - consider audio book
  - Bowker for ISBN number
  - library of Congress cataloging in publication number - pcn number
  - test a traditional direct mail sales offer
  - how can I embiggen my weekly email list audience?
  - 


# Book Printing

The Manifesto
Printed by Color House Graphics in MI
Fulfillment (to Amazon) by JPL (https://www.jplbooks.com/pages/fulfillment-1)

Pricing Creativity
Binders printed by Corporate Image (https://www.corp-image.com/)
Fulfillment and insert/tab printing by Bodnar Printing Company (https://www.bodnarprinting.com/)