---
subtitle: "Philip Morgan Consulting Client Briefing"
title: "Learning about book publishing"
author: "Philip Morgan"
date: November 2, 2019 - v1.0
abstract: |
  I've been learning about professional self-publishing from someone who runs a boutique imprint. In this briefing I share what I've learned with you.
fontsize: 13pt
urlcolor: blue
output:
  tufte::tufte_handout:
    toc: true
    toc_depth: 2
  tufte::tufte_html:
    toc: true
    toc_depth: 2
---

# Introduction

In early October, 2019 I joined a writing retreat with 3 other business owners. One runs a boutique publishing imprint. On the drive back from the cabin to the airport, I grilled him with questions about book publishing.

Here's what I learned. Most of it is written as if he's speaking, and it's based on notes I made during the conversation rather than my rusty memory. In places where I need to mix in my voice/perspective/experience, I'll call that out as a "Note from Philip".

# Cover design

Use <https://www.faceoutstudio.com>. They've designed more NYT Best Seller list book covers than any other studio.

## Note from Philip

I'm in talks with Faceout now about a cover for TPM v3. Here's what I've learned about their pricing, copied from an email thread. ^[No guarantees this will be true months or years from now, but it's current as of October 2019.]

> We work mainly with large trade publishers, but really enjoy working with smaller, independent presses and/or individuals when its the right fit. Our average cover design fee is $2,500. Depending on the scope, our cover design fees typically fall in the $2,000 - $3,000 range. We design/ typeset interiors for $10/ page (assuming simple, running text). 
> 
> If that budget range is in line w/ your expectations, we can discuss process over the phone whenever convenient for you. If that budget is outside of what you had in mind, I have one other option for your consideration. I have a secondary business platform whereby I tap into one of our senior designers who can produce covers for you as a freelancer. In this model, I can cut our normal studio fee in half, but the process will look a little different. This solution is contingent on their availability.
> 
> Designer: I have 3 designers that work offline this way. See below (scroll down to see their work).
> 
> **Tim Green**: <https://www.faceoutstudio.com/team/tim-green.shtml>
> 
> **Jeff Miller**: <https://www.faceoutstudio.com/team/jeff-miller.shtml>
> 
> **Lindy Martin**: <https://www.faceoutstudio.com/team/lindy-martin.shtml>
> 
> **Budget / Billing**:
> 
> The basic fee structure we’d be proposing is as follows:
> 
> - $300 per unique cover concept (you can decide how many options you want to see on the front end)
> - $300 for the mechanical prep (spine, back cover, print ready files)
> - $300 for project management
> 
> If we can solve your cover with the first cover presented, your total cost would be $900. If you want to see 2 unique cover options up front or need a second one produced, your fee would be $1,200 …. and so forth. 
> 
> We 2-part bill ––half up front to be paid before the delivery of the initial comps and then the remaining when we close out the project. Billing will be issued by me under the business name,  Esperto Creative LLC
> 
> Schedule: TBD
> 
> **Next Steps**:
> 
> 1. Fill out and send back project brief document (I will send if you’d like to move this forward). I will review w/ your designer of choice and confirm if we’re on board or not, and propose a delivery schedule
> 2. Decide on how many comps you’d like to see in the initial cover presentation
> 3. Pay the first installment from first invoice
> 4. I’ll set up a call for you to chat with the designer (this will set the cover design process in motion)
> 5. Once an initial cover is approved, we will need the following from you to complete your cover
> - Final confirmation of trim size (so as to select the right template)
> - All front cover copy
> - Spine copy
> - Imprint logo
> - Backcover copy
> - Endorsements for the back cover if you have them
> - ISBN and barcode (we can create the barcode for you)
> - Author bio and photo if needed.
> - We’ll upload your cover to your publishing platform
> 7. We can recommend an interior designer; we work with a lot if you need help there.
> 
> **Lead Time**
> as an average … we need at least 2 week to get a new job scheduled, assigned, designed and initial cover comps presented. Maybe 1-2 week for revisions as needed, 3 days for interior design template, then maybe 5 days for full interior layout and final files prep. So …. approximately 4-5 weeks

# Front matter

The appearance of your front matter has an outsized impact since if you offer a sample chapter (you should do that too), the front matter is part of the sample chapter first impression.

Just mirror exactly what you see traditionally published books doing. Hell, copy what I do in my books!

# Printing

Printing quality sends a signal about professionalism and expertise, so don't cheap out here.

The sweet spot is 70 to 85lb text paper -- matte coated for a luxe feel, or uncoated for a more workaday feel. ^[Note from Philip: 85lb or 105lb *gloss* coated will give you a vivid flashback to the National Geographic magazines you read as a kid.]

If you're publishing a ring-bound manual, or a wire-bound manual, consider page lifters as section separators. Lifters help with the UX.

If you're publishing a ring-bound manual and sourcing the printed pages seperately from the binder, print on pre-drilled paper. Binders may also need to be shrink wrapped to better survive shipping.

On the subject of shipping cost, think and research deeply about what it will take to ship something heavy, like a 3-ring binder publication, internationally.

# Microsite

Create a microsite just for the book, both for ease of promotion during speaking/podcast guesting and for the professional signal it sends.

# Blurbs

Yeah, blurbs are a game, but they're a game you should play.

Ask about 20 people for blurbs. Give them a desired word count, and a 2 to 3-week deadline.

# Vanity imprint

Do create a vanity imprint. ^[<https://www.authorimprints.com/cost-create-self-publishing-imprint/>]

Do get an ISBN number. ^[<https://www.myidentifiers.com/identify-protect-your-book/isbn/buy-isbn>]

Do get a Library of Congress PCN number. ^[<https://www.storiestotellbooks.com/blog/get-a-library-of-congress-number-for-your-book.html>]

# Reviews

Reviews are a game, but they are a game you should play. Consider pay for play reviews. Use this company: <https://www.kirkusreviews.com/indie-reviews/>

# Author portrait

Do invest in a pro author portrait.

# Sample chapter

Do provide a sample chapter folks can download from the book's microsite, possibly gated behind an opt-in so you can communicate with those who downloaded a sample chapter. Do include the front and back matter in the sample.

# Audio book

Do consider recording an audio book and releasing it in tandem with the other book format(s).

# Launch and promotion

Doing a launch is important, especially if you offer a special price during launch.

Do invest in social media amplification.

# Conclusion

A lot of this is "do this" guidance, without any supporting "why" details, and with no details about exactly how to do it. My source for this has seen a lot more of the publishing industry, as both a functionally self-published author and as publisher for others, than I have. So in short, I trust him to give good answers to my questions, and for those answers to be relevant to the kind of context I'm operating in. That's both why I didn't press him for "why" details, and why I'm passing along his guidance in concise "do this" form to you. This is, after all, a _brief_ ing. :)

I hope it helps when the day comes that you're ready to publish a book based on your expertise and point of view.